title: Sheila Chairvolotti # your name (or website title) here
logo: "https://github.com/SChairv/SChairv.github.io/blob/master/images/309801223_626897278987417_7678680566408899643_n.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  "Highlighting some of the data analysis projects I have completed and experimented with."
  <br>
  I'm a post-homeschooling mom with a background in biology and environmental studies. I'm taking courses and learning different aspects of data analysis, looking to re-enter the fulltime workforce through a remote data analyst position.<br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/sheila-chairvolotti-ab899b1b1/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
